<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Exercise;


/**
 * ExpositorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends EntityRepository
{
  public function chooseExercise($user)
  {
      /*
        DQL são relacionados as variaveis
      */
      $qString = "SELECT e from AppBundle:Exercise e where e.id not in
        (SELECT m.exercise from AppBundle:Movement m where m.user = ".$user.")";
      $query = $this->getEntityManager()->createQuery($qString);
      $exercises = $query->getResult();

      $last = \count($exercises) - 1;
      $exerciseIndex = mt_rand(0, $last );

      return $exercises[$exerciseIndex];
  }
}
