<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends EntityRepository
{
    public function getActionWithComments($actionId){
        $commentsActionRepository = $this->getEntityManager()->getRepository('AppBundle:CommentsAction');
        foreach ($commentsActionRepository->findBy(array('action' => $actionId)) as $comment ){
            $action->addComment($comment);
        }
        return $action;
        
    }
    
}
