<?php

namespace AppBundle\Repository;

/**
 * SeguirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguirRepository extends \Doctrine\ORM\EntityRepository
{
}
