<?php

namespace Application\Sonata\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConexaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
}
